### PR TITLE
hu_HU.properties

### PR DESCRIPTION
**Pull request by TheAdamYT**

### CODE REVIEW

**Review by FlorianMichael — APPROVED** [review]
Thank you!

**Comment by TheAdamYT** [comment]
> Thank you!

np. when it will get added? if it will xd

**Comment by RaphiMC** [comment]
This will be in the next release (And I will make a new release this week)

**Comment by TheAdamYT** [comment]
> This will be in the next release (And I will make a new release this week)

okay ty

**Pull request merged**
